// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDN1I7o8hFYpHzksyHF0eVjHB89iwqh4o',
    appId: '1:1038498402862:web:1c4874826c637e93e545bf',
    messagingSenderId: '1038498402862',
    projectId: 'instagram-47746',
    authDomain: 'instagram-47746.firebaseapp.com',
    databaseURL: 'https://instagram-47746-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'instagram-47746.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdiVJJb5K7IMe-SC9yfcKg398Lv-p76jE',
    appId: '1:1038498402862:android:6f58f908bcf01d76e545bf',
    messagingSenderId: '1038498402862',
    projectId: 'instagram-47746',
    databaseURL: 'https://instagram-47746-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'instagram-47746.appspot.com',
  );
}
